/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaccesscontrol;

import capaccesscontrol.config.CAPConfig;
import capaccesscontrol.packet.CAPReponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Edwin Carmona
 */
public class CAPMainUI extends javax.swing.JFrame {
    
    private final CAPConfig oConfig;

    /**
     * Creates new form CAPMainUI
     * @param config
     */
    public CAPMainUI(CAPConfig config) {
        oConfig = config;
        initComponents();
        startClock();
        setImage();
        getData();
    }

    public void startClock() {
        SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyy HH:mm:ss");
        
        javax.swing.Timer t = new javax.swing.Timer(1000,
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();

                jTextField1.setText(format1.format(now.getTime()));
                jTextField1.setHorizontalAlignment(jTextField1.CENTER);
                // Center the text
                jTextField1.getCaret().setVisible(false);
                // Hide the Cursor in JTextField
            }
        });
        
        t.start();
    }
    
    public void setImage() {
        jLImage.setIcon(new javax.swing.ImageIcon(oConfig.getCompanyData().getCompanyImage())); // NOI18N
        jLImage.setPreferredSize(new java.awt.Dimension(300, 23));
    }
    
    public void getData() {
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            DateFormat tf = new SimpleDateFormat("HH:mm");
            
            String charset = java.nio.charset.StandardCharsets.UTF_8.name();
            String sDate = df.format(new Date());
            String sTime = tf.format(new Date());
            
            String query = String.format("dt_date=%s&dt_time=%s&num_emp=%s&next_days=%s",
                    URLEncoder.encode(sDate, charset),
                    URLEncoder.encode(sTime, charset),
                    URLEncoder.encode("990", charset),
                    URLEncoder.encode("7", charset)
            );
            
            String sURL = "http://localhost:9090/cap/public/api/infobynum";
            
            URLConnection connection = new URL(sURL + "?" + query).openConnection();
            connection.setRequestProperty("Accept-Charset", charset);
            connection.setRequestProperty("Content-Type", "application/json");
            InputStream response = connection.getInputStream();
            
            try (Scanner scanner = new Scanner(response)) {
                String responseBody = scanner.useDelimiter("\\A").next();
                System.out.println(responseBody);
                
                ObjectMapper mapper = new ObjectMapper();
                CAPReponse capResponse = mapper.readValue(responseBody, CAPReponse.class);
                System.out.println(capResponse);
            }
        }   catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CAPMainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CAPMainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CAPMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLImage = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new java.awt.GridLayout(7, 1));

        jLabel1.setText("CAP Access Control");
        jPanel7.add(jLabel1);

        jPanel5.add(jPanel7);

        jLImage.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel8.add(jLImage);

        jPanel5.add(jPanel8);

        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel9.add(jTextField1);

        jPanel5.add(jPanel9);
        jPanel5.add(jPanel10);
        jPanel5.add(jPanel11);
        jPanel5.add(jPanel12);
        jPanel5.add(jPanel13);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 300));
        jPanel2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 306, -1, 283));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitácora de consulta"));
        jPanel3.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 240, 589));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
